require('./setup')();
require('./test.batch');
require('./test.convertTypes');
require('./test.cli');
require('./test.item');
require('./test.table');
require('./test.kinesis');
require('./test.multi');
require('./test.config');
