require('./setup')();
require('./test.scan');
require('./test.filter');
require('./test.batch');
require('./test.convertTypes');
require('./test.item');
require('./test.table');
require('./test.kinesis');
require('./test.multi');
